# 定义Prettier的配置选项
semi: true # 在语句末尾添加分号
tabWidth: 2 # 每个缩进级别的空格数
useTabs: false # 是否使用制表符而不是空格进行缩进
quoteProps: "as-needed" # 仅在需要时为对象属性添加引号
singleQuote: false # 使用单引号而不是双引号
jsxSingleQuote: false # 在JSX中使用单引号
trailingComma: "es5" # 在ES5中添加尾随逗号
bracketSpacing: true # 在对象，数组括号和函数参数周围添加空格
bracketSameLine: true # 将对象或函数的括号放在与声明同一行
arrowParens: "avoid" # 尽可能避免在箭头函数参数周围添加括号
printWidth: 150 # 格式化代码的宽度限制
