export const provider = [
  {
    name: "Nuxt",
    url: "https://nuxt.com/",
    iconL: "/icon/other/nuxt.svg",
    iconD: "/icon/other/nuxt.svg",
    description: "网站基于 Nuxt 构建.",
  },
  {
    name: "golang",
    url: "https://golang.google.cn/",
    iconL: "/icon/other/golang-svgrepo-com.svg",
    iconD: "/icon/other/golang-svgrepo-com.svg",
    description: "网站基于 golang 构建后台 api.",
  },
  {
    name: "Tailwind CSS",
    url: "https://tailwindcss.com/",
    iconL: "/icon/other/tailwindcss.svg",
    iconD: "/icon/other/tailwindcss.svg",
    description: "样式基于 Tailwind CSS 实现.",
  },
  {
    name: "Vercel",
    url: "https://vercel.com/",
    iconL: "/icon/other/vercel-l.webp",
    iconD: "/icon/other/vercel-d.webp",
    description: "网站托管在 Vercel, Free Plan.",
  },
  {
    name: "Supabase",
    url: "https://supabase.com/",
    iconL: "/icon/other/supabase.svg",
    iconD: "/icon/other/supabase.svg",
    description: "数据保存在 Supabase, Free Plan.",
  },
  {
    name: "Cloudimage",
    url: "https://www.cloudimage.io/",
    iconL: "/icon/other/cloudimage-light.svg",
    iconD: "/icon/other/cloudimage.png",
    description: "大图片分流, Free Plan.",
    iconIsLen: true,
  },
  {
    name: "GitHub",
    url: "https://github.com/",
    iconL: "/icon/other/github-l.webp",
    iconD: "/icon/other/github-d.webp",
    description: "代码托管.",
  },
  {
    name: "Steam",
    url: "https://store.steampowered.com/",
    iconL: "/icon/other/steam.svg",
    iconD: "/icon/other/steam.svg",
    description: "通过 API 获取游戏列表.",
  },
  {
    name: "中文网字计划",
    url: "https://chinese-font.netlify.app/",
    iconL: "/icon/other/chinese-font.netlify.app.ico",
    iconD: "/icon/other/chinese-font.netlify.app.ico",
    description: "使用字体：“抖音美好体”.",
  },
];